# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2016

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  works: /works
#  Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  search: false
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  # license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: true
  qrCode: 
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: zxshen@qq.com
  stack-overflow: https://segmentfault.com/u/zxshen
  twitter:
  facebook:
  linkedin: http://www.linkedin.com/in/zxshen
  google:
  github: https://github.com/zxui
  weibo: 
  zhihu: https://www.zhihu.com/people/zxui
  pocket:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 97199f458716988abad8acf1a0a0dc49
# Google Analytics
# google_analytics: UA-74273646-1

# Duoshuo
# duoshuo_shortname: ahonn
# Disqus
# disqus_shortname:
# netease
netease_key: f2fa1598c04f4a84933d6689c0be9af9


# ===========================================
# Version
# ===========================================
version: 2.3.x
